"""empty message

Revision ID: 528ea4fe6b5c
Revises: 006395fa608e
Create Date: 2023-06-11 16:51:59.050021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528ea4fe6b5c'
down_revision = '006395fa608e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pswd', sa.String(length=32), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
