"""empty message

Revision ID: 864ce4abcd61
Revises: b53aa6ec8a93
Create Date: 2023-06-08 17:07:40.526284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864ce4abcd61'
down_revision = 'b53aa6ec8a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'position', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    op.drop_table('position')
    # ### end Alembic commands ###
